swagger: "2.0"
info:
  title: Thurloe
  description: All your key-value pairs are belong to us
  version: "0.2"
paths:
  /status:
    get:
      operationId: status
      tags:
      - Status
      summary: Returns status code for connection to database.
      produces:
      - application/json
      responses:
        200:
          description: OK
        500:
          description: Internal server error
  /api/thurloe:
    get:
      operationId: query
      summary: Query the database using a custom subset of userId, key and value
      produces:
        - application/json
        - text/plain
      parameters:
        - name: X-FireCloud-Id
          in: header
          description: FireCloud ID Token to be passed as a header
          required: true
          type: string
        - name: userId
          description: User ID of the owner of the key-value pair
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          in: query
        - name: key
          description: Key of the key-value pair
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          in: query
        - name: value
          description: Value of the key-value pair
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          in: query
      tags:
        - Key-value pairs
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
          examples:
            application/json:
              -
                userId: 123
                keyValuePair:
                  key: foo
                  value: bar
        400:
          description: Bad Request (e.g. missing or invalid "X-FireCloud-Id" header)
        500:
          description: Internal server error
      security:
        - google_oauth:
            - openid
    post:
      operationId: setKey
      summary: Adds or resets a list of key-value pair to the database for a given user ID.
      produces:
        - application/json
        - text/plain
      consumes:
      - application/json
      parameters:
      - name: X-FireCloud-Id
        in: header
        description: FireCloud ID Token to be passed as a header
        required: true
        type: string
      - name: body
        in: body
        description: The Key/Value pair to add to the system
        schema:
          type: object
          required:
            - userId
            - keyValuePairs
          properties:
            userId:
              type: string
            keyValuePairs:
              type: array
              items:
                type: object
                required:
                  - key
                  - value
                properties:
                  key:
                    type: string
                  value:
                    type: string
      tags:
        - Key-value pairs
      responses:
        200:
          description: OK
        400:
          description: Bad request (e.g. invalid JSON input, missing or invalid "X-FireCloud-Id" header)
        500:
          description: Internal server error
      security:
        - google_oauth:
            - openid
  /api/thurloe/{userId}:
    get:
      operationId: getAll
      summary: Returns a list of all keys and values stored in Thurloe for the specified user ID.
      produces:
        - application/json
        - text/plain
      parameters:
      - name: X-FireCloud-Id
        in: header
        description: FireCloud ID Token to be passed as a header
        required: true
        type: string
      - name: userId
        in: path
        description: The user ID whose data is being requested
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              userId:
                type: string
              keyValuePairs:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
        400:
          description: Bad Request (e.g. missing or invalid "X-FireCloud-Id" header)
        500:
          description: Internal server error
      tags:
        - Key-value pairs
      security:
        - google_oauth:
            - openid
  /api/thurloe/{userId}/{key}:
    get:
      operationId: getKvp
      summary: Returns a single key-value pair, looked up by key and userId.
      produces:
        - application/json
        - text/plain
      parameters:
      - name: X-FireCloud-Id
        in: header
        description: FireCloud ID Token to be passed as a header
        required: true
        type: string
      - name: userId
        in: path
        description: The user ID whose data is being requested
        required: true
        type: string
      - name: key
        in: path
        description: The key of the data to return
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              userid:
                type: string
              keyValuePair:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
        400:
          description: Bad Request (e.g. missing or invalid "X-FireCloud-Id" header)
        404:
          description: Key not found
        500:
          description: Internal server error
      tags:
        - Key-value pairs
      security:
        - google_oauth:
            - openid
    delete:
      operationId: deleteKvp
      summary: Deletes a single key-value pair, referenced by key and userId.
      produces:
        - application/json
        - text/plain
      parameters:
      - name: X-FireCloud-Id
        in: header
        description: FireCloud ID Token to be passed as a header
        required: true
        type: string
      - name: userId
        in: path
        description: The user ID whose data is being deleted
        required: true
        type: string
      - name: key
        in: path
        description: The key of the data to delete
        required: true
        type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request (e.g. missing or invalid "X-FireCloud-Id" header)
        404:
          description: Key not found
        500:
          description: Internal server error
      tags:
        - Key-value pairs
      security:
        - google_oauth:
            - openid
  /api/notification:
    post:
      operationId: postNotification
      summary: Sends a notification to the specified user with the templateId and substitutions specified
      produces:
        - text/plain
      parameters:
      - name: X-FireCloud-Id
        in: header
        description: FireCloud ID Token to be passed as a header
        required: true
        type: string
      - name: body
        in: body
        description: The notification to send
        schema:
          type: object
          required:
            - notificationId
          properties:
            userId:
              type: string
            userEmail:
              type: string
            replyTo:
              type: string
            notificationId:
              type: string
            substitutions:
              type: object
              properties:
                key:
                  type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request (e.g. missing or invalid "X-FireCloud-Id" header)
        500:
          description: Internal server error
      tags:
        - Notifications
      security:
        - google_oauth:
            - openid
securityDefinitions:
  google_oauth:
    type: oauth2
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    flow: implicit
    scopes:
      openid: open id authorization
