swagger: "2.0"
info:
  title: Thurloe
  description: All your key/value pairs are belong to us
  version: 0.2
basePath: /api
paths:
  /thurloe:
    get:
      operationId: query
      summary: Query the database using a custom subset of userId, key and value
      produces:
        - text/plain
        - application/json
      parameters:
        - name: userId
          description: User ID of the owner of the key/value pair
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          in: query
          description: >
            Show only (User,(Key,Value)) items which are assigned to this user ID
        - name: key
          description: Key of the key/value pair
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          in: query
          description: >
            Show only (User,(Key,Value)) items which have this key
        - name: value
          description: Value of the key/value pair
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          in: query
          description: >
            Show only (User,(Key,Value)) items which have this value
      tags:
        - Key/value pairs
      responses:
        200:
          description: OK
          produces:
          - application/json
          schema:
            type: array
            items:
              "type": "object"
          examples:
            application/json: |-
              [{
                "userId": "string",
                "keyValuePair": {
                  "key": "string",
                  "value": "string"
                }
              }]
        500:
          description: Internal server error
          produces: text/plain
      tags:
        - Key/value pairs
      security:
        - google_oauth:
            - openid
    post:
      operationId: setKey
      summary: Adds or resets a single key/value pair to the database for a given user ID.
      produces:
        - text/plain
        - application/json
      consumes:
      - application/json
      parameters:
      - name: body
        in: body
        description: The Key/Value pair to add to the system
        required: true
        type: string
        schema:
          {
            "type": "object",
            "required": ["key", "value"],
            "properties": {
              "userId": {
                "type": "string"
              },
              "keyValuePair": {
                "type": "object",
                "required": [ "key", "value" ],
                "properties": {
                  "key": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                }
              }
            }
          }
      tags:
        - Key/value pairs
      responses:
        200:
          description: OK
        400:
          description: Bad request (e.g. invalid JSON input)
        500:
          description: Internal server error
      security:
        - google_oauth:
            - openid
  /status:
    get:
      operationId: status
      tags:
      - Status
      summary: Returns status code for connection to database.
      produces:
      - text/plain
      responses:
        200:
          description: OK
        500:
          description: Internal server error
  /thurloe/{userId}:
    get:
      operationId: getAll
      summary: Returns a list of all keys and values stored in Thurloe for the specified user ID.
      produces:
        - text/plain
        - application/json
      parameters:
      - name: userId
        in: path
        description: The user ID whose data is being requested
        required: true
        type: string
      responses:
        200:
          description: OK
          produces:
          - application/json
          - text/plain
          schema:
            {
              "properties": {
                "userId": {
                  type: "string"
                },
                "keyValuePairs": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": [ "key", "value" ],
                    "properties": {
                      "key": {
                        "type": "string"
                      },
                      "value": {
                        "type": "string"
                      }
                    }
                  }
                }
              },
              "type": "object",
              "required": [ "userId", "keyValuePairs" ]
            }
        500:
          description: Internal server error
          produces: text/plain
      tags:
        - Key/value pairs
      security:
        - google_oauth:
            - openid
  /thurloe/{userId}/{key}:
    get:
      operationId: getKvp
      summary: Returns a single key/value pair, looked up by key and userId.
      produces:
        - text/plain
        - application/json
      parameters:
      - name: userId
        in: path
        description: The user ID whose data is being requested
        required: true
        type: string
      - name: key
        in: path
        description: The key of the data to return
        required: true
        type: string
      responses:
        200:
          description: OK
          produces:
            - application/json
          schema:
            {
              "type": "object",
              "required": ["key", "value"],
              "properties": {
                "userId": {
                  "type": "string"
                },
                "keyValuePair": {
                  "type": "object",
                  "required": [ "key", "value" ],
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  }
                }
              }
            }
        404:
          description: Key not found
          produces:
          - text/plain
        500:
          description: Internal server error
          produces:
          - text/plain
      tags:
        - Key/value pairs
      security:
        - google_oauth:
            - openid
    delete:
      operationId: deleteKvp
      summary: Deletes a single key/value pair, referenced by key and userId.
      produces:
        - text/plain
        - application/json
      produces:
      - text/plain
      parameters:
      - name: userId
        in: path
        description: The user ID whose data is being deleted
        required: true
        type: string
      - name: key
        in: path
        description: The key of the data to delete
        required: true
        type: string
      responses:
        200:
          description: OK
        404:
          description: Key not found
        500:
          description: Internal server error
      tags:
        - Key/value pairs
      security:
        - google_oauth:
            - openid
  /notification:
    post:
      operationId: postNotification
      summary: Sends a notification to the specified user with the templateId and substitutions specified
      produces:
        - text/plain
      parameters:
      - name: body
        in: body
        description: The notification to send
        required: true
        type: string
        schema:
          {
            "type": "object",
            "required": ["userId", "notificationId"],
            "properties": {
              "userId": {
                "type": "string"
              },
              "notificationId": {
                "type": "string"
              },
              "substitutions": {
                "type": "object",
                "properties": {
                  "key": {
                    "type": "string",
                    "default": "value"
                  }
                }
              }
            }
          }
      responses:
        200:
          description: OK
          produces:
            - text/plain
        500:
          description: Internal server error
          produces:
          - text/plain
      tags:
        - Notifications
      security:
        - google_oauth:
            - openid
securityDefinitions:
  google_oauth:
    type: oauth2
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    flow: implicit
    scopes:
      openid: open id authorization
