swagger: "2.0"
info:
  title: Thurloe Service
  version: 0.1
paths:
  /thurloe/{userId}:
    get:
      operationId: getAll
      summary: Returns a list of all keys and values stored in Thurloe for the specified user ID.
      produces:
      - application/json
      - text/plain
      parameters:
      - name: userId
        in: path
        description: The user ID whose data is being requested
        required: true
        type: string
      responses:
        200:
          description: OK
        500:
          description: Internal server error
    post:
      operationId: setKey
      summary: Adds or resets a single key/value pair to the database for the given user ID.
      produces:
      - text/plain
      consumes:
      - application/json
      parameters:
      - name: UserId
        in: path
        description: The user ID to store this data against
        required: true
        type: string
      - name: body
        in: body
        description: The Key/Value pair to add to the system
        required: true
        type: string
        schema:
          {
            "properties": {
              "key": {
                "type": "string"
              },
              "value": {
                "type": "string"
              }
            },
            "required": ["key", "value"],
            "type": "object"
          }
      responses:
        200:
          description: OK
        400:
          description: Bad request (e.g. invalid JSON input)
        500:
          description: Internal server error
  /thurloe/{userId}/{key}:
    get:
      operationId: getKvp
      summary: Returns a single key/value pair, looked up by key and userId.
      produces:
      - application/json
      - text/plain
      parameters:
      - name: userId
        in: path
        description: The user ID whose data is being requested
        required: true
        type: string
      - name: key
        in: path
        description: The key of the data to return
        required: true
        type: string
      responses:
        200:
          description: OK
        404:
          description: Key not found
        500:
          description: Internal server error
    delete:
      operationId: deleteKvp
      summary: Deletes a single key/value pair, referenced by key and userId.
      produces:
      - text/plain
      parameters:
      - name: userId
        in: path
        description: The user ID whose data is being deleted
        required: true
        type: string
      - name: key
        in: path
        description: The key of the data to delete
        required: true
        type: string
      responses:
        200:
          description: OK
        404:
          description: Key not found
        500:
          description: Internal server error