name: Scala tests with coverage

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [develop]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      # coursier cache action caches both coursier and sbt caches
      - name: coursier-cache-action
        uses: coursier/cache-action@v5

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Run tests
        # see https://github.com/sbt/sbt/issues/6447 re: sbt opts in this command
        run: sbt -Dsbt.boot.directory=/tmp/boot1 -Dsbt.launcher.coursier=false jacoco

      - uses: codecov/codecov-action@v1
